-- Uncomment the following line if recreating the table
-- DROP TABLE POSTCARDS;
CREATE TABLE POSTCARDS(
    USER_USERNAME VARCHAR(15) NOT NULL,
    STATUS_TEXT VARCHAR(140) NOT NULL,
    STATUS_TITLE VARCHAR(140) NOT NULL,
    IMAGE_NAME VARCHAR(50) NOT NULL,
    TIME_STAMP VARCHAR(50) NOT NULL,
    PRIMARY KEY (TIME_STAMP)
);

CREATE TABLE COMMENTS(
    TIME_STAMP VARCHAR(50) NOT NULL,
    USERNAME VARCHAR(15) NOT NULL,
    CONTENT VARCHAR(140) NOT NULL,
    IMAGE_NAME VARCHAR(50) NOT NULL,
    PARENT_TS VARCHAR(50) NOT NULL,
    FOREIGN KEY (PARENT_TS) REFERENCES POSTCARDS(TIME_STAMP)
);